openapi: 3.0.3
info:
  title: STD24182 - Exo1
  version: '1.0.0'

servers:
  - url: http://127.0.0.1:8000

paths:
  /ping:
    get:
      summary: Retourne Pong
      responses:
        "200":
          description: afficher pong
          content:
            text/plain:
              schema:
                type: string
