openapi: 3.0.3
info:
  title: STD24182 - Exo2
  version: "1.0.0"

servers:
  - url: http://127.0.0.1:8000

paths:
  /users:
    get:
      summary: Récupérer une liste d'utilisateurs avec pagination
      parameters:
        - name: page
          in: query
          required: true
          schema:
            type: integer
            example: 1
        - name: size
          in: query
          required: true
          schema:
            type: integer
            example: 20
      responses:
        "200":
          description: Liste des utilisateurs retrouvés
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
        "400":
          description: Mauvais types de paramètres fournis
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Bad types for provided query parameters

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Alice
        email:
          type: string
          format: email
          example: alice@example.com
